#!/usr/bin/env node

var util = require('util');

var async = require('async');

var SensorTag = require('sensortag');

var data = {}

var program = parseArgv(process.argv)
console.log(program)

var USE_READ = true;

SensorTag.discover(function(sensorTag) {
  console.log('discovered: ' + sensorTag);

  sensorTag.on('disconnect', function() {
    console.log('disconnected!');
    process.exit(0);
  });

  async.series([
      function(callback) {
        console.log('connectAndSetUp');
        sensorTag.connectAndSetUp(callback);
      },
      function(callback) {
        console.log('readDeviceName');
        sensorTag.readDeviceName(function(error, deviceName) {
          console.log('\tdevice name = ' + deviceName);
          callback();
        });
      },
      function(callback) {
        console.log('readSystemId');
        sensorTag.readSystemId(function(error, systemId) {
          console.log('\tsystem id = ' + systemId);
          callback();
        });
      },
      function(callback) {
        console.log('readSerialNumber');
        sensorTag.readSerialNumber(function(error, serialNumber) {
          console.log('\tserial number = ' + serialNumber);
          callback();
        });
      },
      function(callback) {
        console.log('readFirmwareRevision');
        sensorTag.readFirmwareRevision(function(error, firmwareRevision) {
          console.log('\tfirmware revision = ' + firmwareRevision);
          callback();
        });
      },
      function(callback) {
        console.log('readHardwareRevision');
        sensorTag.readHardwareRevision(function(error, hardwareRevision) {
          console.log('\thardware revision = ' + hardwareRevision);
          callback();
        });
      },
      function(callback) {
        console.log('readSoftwareRevision');
        sensorTag.readHardwareRevision(function(error, softwareRevision) {
          console.log('\tsoftware revision = ' + softwareRevision);
          callback();
        });
      },
      function(callback) {
        console.log('readManufacturerName');
        sensorTag.readManufacturerName(function(error, manufacturerName) {
          console.log('\tmanufacturer name = ' + manufacturerName);
          callback();
        });
      },
      function(callback) {
        if (program.objectTemperature || program.ambientTemperature || program.allSensors) {
          console.log('enableIrTemperature');
          sensorTag.enableIrTemperature(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.objectTemperature || program.ambientTemperature || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.objectTemperature || program.ambientTemperature || program.allSensors) {
          console.log('readIrTemperature');
          sensorTag.readIrTemperature(function(error, objectTemperature, ambientTemperature) {
            if (program.objectTemperature || program.allSensors) {
              data.objectTemperature = objectTemperature.toFixed(1)
              console.log('\tobject temperature = %d °C', objectTemperature.toFixed(1));
            }
            if (program.ambientTemperature || program.allSensors) {
              data.ambientTemperature = ambientTemperature.toFixed(1)
              console.log('\tambient temperature = %d °C', ambientTemperature.toFixed(1));
            }
            callback();
          });
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.objectTemperature || program.ambientTemperature || program.allSensors) {
          console.log('disableIrTemperature');
          sensorTag.disableIrTemperature(callback);
        }
      },
      function(callback) {
        if (program.accelerometer || program.allSensors) {
          console.log('enableAccelerometer');
          sensorTag.enableAccelerometer(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.accelerometer || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.accelerometer || program.allSensors) {
          console.log('readAccelerometer');
          sensorTag.readAccelerometer(function(error, x, y, z) {
            data.accelerometer_x = x.toFixed(1)
            data.accelerometer_y = y.toFixed(1)
            data.accelerometer_z = z.toFixed(1)
            console.log('\tx = %d G', x.toFixed(1));
            console.log('\ty = %d G', y.toFixed(1));
            console.log('\tz = %d G', z.toFixed(1));
            callback();
          });
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.accelerometer || program.allSensors) {
          console.log('disableAccelerometer');
          sensorTag.disableAccelerometer(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.humidity || program.allSensors) {
          console.log('enableHumidity');
          sensorTag.enableHumidity(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.humidity || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.humidity || program.allSensors) {
          console.log('readHumidity');
          sensorTag.readHumidity(function(error, temperature, humidity) {
            data.humidityTemperature = temperature.toFixed(1)
            data.humidityHumidity = humidity.toFixed(1)
            console.log('\ttemperature = %d °C', temperature.toFixed(1));
            console.log('\thumidity = %d %', humidity.toFixed(1));
            callback();
          });
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.humidity || program.allSensors) {
          console.log('disableHumidity');
          sensorTag.disableHumidity(callback);
        }
      },
      function(callback) {
        if (program.magnetometer || program.allSensors) {
          console.log('enableMagnetometer');
          sensorTag.enableMagnetometer(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.magnetometer || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.magnetometer || program.allSensors) {
          console.log('readMagnetometer');
          sensorTag.readMagnetometer(function(error, x, y, z) {
            data.magnetometer_x = x.toFixed(1)
            data.magnetometer_y = y.toFixed(1)
            data.magnetometer_z = z.toFixed(1)
            console.log('\tx = %d μT', x.toFixed(1));
            console.log('\ty = %d μT', y.toFixed(1));
            console.log('\tz = %d μT', z.toFixed(1));
            callback();
          });
        } else {
          callback()
        }
      },
      function(callback) {
        if (program.magnetometer || program.allSensors) {
          console.log('disableMagnetometer');
          sensorTag.disableMagnetometer(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.barometricPressure || program.allSensors) {
          console.log('enableBarometricPressure');
          sensorTag.enableBarometricPressure(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.barometricPressure || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.barometricPressure || program.allSensors) {
          console.log('readBarometricPressure');
          sensorTag.readBarometricPressure(function(error, pressure) {
            data.barometricPressure = pressure.toFixed(1)
            console.log('\tpressure = %d mBar', pressure.toFixed(1));
            callback();
          });
        } else {
          callback()
        }
      },
      function(callback) {
        if (program.barometricPressure || program.allSensors) {
          console.log('disableBarometricPressure');
          sensorTag.disableBarometricPressure(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.gyroscope || program.allSensors) {
          console.log('enableGyroscope');
          sensorTag.enableGyroscope(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.gyroscope || program.allSensors) {
          setTimeout(callback, 2000);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (program.gyroscope || program.allSensors) {
          console.log('readGyroscope');
          sensorTag.readGyroscope(function(error, x, y, z) {
            data.gyroscope_x = x.toFixed(1)
            data.gyroscope_y = y.toFixed(1)
            data.gyroscope_z = z.toFixed(1)
            console.log('\tx = %d °/s', x.toFixed(1));
            console.log('\ty = %d °/s', y.toFixed(1));
            console.log('\tz = %d °/s', z.toFixed(1));
            callback();
          });
        } else {
          callback()
        }
      },
      function(callback) {
        if (program.gyroscope || program.allSensors) {
          console.log('disableGyroscope');
          sensorTag.disableGyroscope(callback);
        }
        else {
          callback()
        }
      },
      function(callback) {
        if (sensorTag.type === 'cc2540') {
          async.series([
            function(callback) {
              console.log('readTestData');
              sensorTag.readTestData(function(error, data) {
                console.log('\tdata = ' + data);

                callback();
              });
            },
            function(callback) {
              console.log('readTestConfiguration');
              sensorTag.readTestConfiguration(function(error, configuration) {
                console.log('\tconfiguration = ' + configuration);

                callback();
              });
            },
            function() {
              callback();
            }
          ]);
        } else if (sensorTag.type === 'cc2650') {
          async.series([
            function(callback) {
              console.log('enableLuxometer');
              sensorTag.enableLuxometer(callback);
            },
            function(callback) {
              setTimeout(callback, 2000);
            },
            function(callback) {
              if (USE_READ) {
                console.log('readLuxometer');
                sensorTag.readLuxometer(function(error, lux) {
                  console.log('\tlux = %d', lux.toFixed(1));

                  callback();
                });
              } else {
                sensorTag.on('luxometerChange', function(lux) {
                  console.log('\tlux = %d', lux.toFixed(1));
                });

                console.log('setLuxometer');
                sensorTag.setLuxometerPeriod(500, function(error) {
                  console.log('notifyLuxometer');
                  sensorTag.notifyLuxometer(function(error) {
                    setTimeout(function() {
                      console.log('unnotifyLuxometer');
                      sensorTag.unnotifyLuxometer(callback);
                    }, 5000);
                  });
                });
              }
            },
            function(callback) {
              console.log('disableLuxometer');
              sensorTag.disableLuxometer(callback);
            },
            function() {
              callback();
            }
          ]);
        } else {
          callback();
        }
      },
      function(callback) {
        log('DATA: ')
        console.log(data)
        console.log('disconnect');
        sensorTag.disconnect(callback);
      }
    ]
  );
});

// This is the standard function for parsing process.argv. It will return
// an object that where `--argumentName` is a property name and the
// proceding argument is the value. If there is no proceeding value then
// it will be interpreted as a boolean true.
function parseArgv(argv) {
  program = {}
  argv.forEach(function(arg, i) {
    if (arg.substr(0, 2) == '--') {
      paramName = arg.substr(2, arg.length)
      nextArg = argv[i+1]
      if ((typeof nextArg == 'string' && nextArg.substr(0, 2) == '--') || nextArg == undefined) {
        program[paramName] = true
      }
      else {
        program[paramName] = nextArg
      }
    }
  })
  return program
}

var log = function(message, tokens) {
  console.log(message, tokens)
}
